### ISSUE TITLE
How to move active bar now?

### ISSUE THREAD

**Issue by LumenzAeternum** [EdwinMindcraft/origins-architectury#430]
I found an issue from 2021. I looked in the configs, but there is only origins-common.toml. How...

**Comment by ChrysanthCow** [comment]
Check through one of the Apoli configs.

**Comment by ChrysanthCow** [comment]
You are able to look through `apoli-client.toml`, which will have:
```toml
[resources_and_cooldowns]
	hud_offset_x = 0
	hud_offset_y = 0
```

Set hud_offset_x and hud_offset_y and you're good to go!
